
- name: Ensure Email Addresses are in Image Form
  hosts: all
  become: true
  tasks:
    - name: Replace "@" with "[at]"
      lineinfile:
        path: /path/to/config/file
        regex: '(.*)@(.*)\.(.*)'
        line: '\1[at]\2[dot]\3'
        backup: yes
      notify:
        - restart_service

    - name: Replace "." with "[dot]"
      lineinfile:
        path: /path/to/config/file
        regex: '(.*)\.([a-zA-Z]+)'
        line: '\1[dot]\2'
        backup: yes
      notify:
        - restart_service

  handlers:
    - name: Restart Service
      service:
        name: your_service_name
        state: restarted

