
- name: Ensure Auditd and Syslogs services are enabled, running, and rotated
  hosts: all
  become: true

  tasks:
    - name: Install Auditd package (Debian/Ubuntu)
      apt:
        name: auditd
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Auditd package (Red Hat/CentOS)
      yum:
        name: audit
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure Auditd service is enabled and running
      service:
        name: auditd
        state: started
        enabled: yes

    - name: Install rsyslog package (Debian/Ubuntu)
      apt:
        name: rsyslog
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install rsyslog package (Red Hat/CentOS)
      yum:
        name: rsyslog
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure rsyslog service is enabled and running
      service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Install logrotate package (Debian/Ubuntu)
      apt:
        name: logrotate
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install logrotate package (Red Hat/CentOS)
      yum:
        name: logrotate
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Configure log rotation for Auditd logs
      copy:
        src: files/auditd-logrotate
        dest: /etc/logrotate.d/auditd
        mode: '0644'

    - name: Configure log rotation for rsyslog logs
      copy:
        src: files/rsyslog-logrotate
        dest: /etc/logrotate.d/rsyslog
        mode: '0644'

