- name: My Playbook
  hosts: all
  become: true
  roles:
    - Web_Server_Application_Hardening
    
  tasks:
    
    - include_tasks: "Web_Server_Application_Hardening/tasks/24_webserver.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/25_webuser.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/26_module.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/27_index.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/28_var.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/29_nginx.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/30_proxy.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/31_token.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/32_mod_security.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/33_remove_default.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/34_syslog.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/35_disable_protocol.yml"
 #up to date


