- name: My Playbook
  hosts: all
  become: true
  roles:
    - OS_Hardening
    - Web_Server_Application_Hardening
    - Database_Server_Hardening
    - Web_Application_Hardening_Activities
  tasks:
    - include_tasks: "OS_Hardening/tasks/*.yml"
    - include_tasks: "Web_Server_Application_Hardening/tasks/*.yml"
    - include_tasks: "Database_Server_Hardening/tasks/*.yml"
    - include_tasks: "Web_Application_Hardening_Activities/tasks/*.yml"

