- name: install ufw
  apt:
    update_cache: yes
    name: ufw
    state: present

- name: Set default firewall policy to deny
  ufw:
    policy: deny

- name: Allow incoming traffic on port 22 (SSH)
  ufw:
    rule: allow
    port: 22

- name: Allow outbound traffic
  ufw:
    direction: outgoing
    policy: allow

